import { IFollower, IStats } from "../types";

export const followers: IFollower[] = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    image: "./streamer1.png",
    isFollowed: true,
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    image: "./streamer2.png",
    isFollowed: false,
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    image: "./streamer3.png",
    isFollowed: false,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    image: "./streamer4.png",
    isFollowed: true,
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    image: "./streamer1.png",
    isVerified: true,
    isFollowed: true,
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    image: "./streamer2.png",
    isFollowed: false,
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    image: "./streamer3.png",
    isFollowed: false,
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    image: "./streamer4.png",
    isFollowed: true,
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    image: "./streamer1.png",
    isFollowed: false,
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    image: "./streamer2.png",
    isFollowed: false,
  },
];
export const following: IFollower[] = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    image: "./streamer1.png",
    isFollowed: true,
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    image: "./streamer2.png",
    isFollowed: true,
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    image: "./streamer3.png",
    isFollowed: true,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    image: "./streamer4.png",
    isFollowed: true,
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    image: "./streamer1.png",
    isFollowed: true,
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    image: "./streamer2.png",
    isFollowed: true,
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    image: "./streamer3.png",
    isFollowed: true,
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    image: "./streamer4.png",
    isFollowed: true,
  },
];

// Stats
export const stats: IStats[] = [
  {
    id: 1,
    image: "./Playstation.svg",
    // title: "Players",
    title : "İstifadəçilər",
    end: 1368,
  },
  {
    id: 2,
    image: "./streamer.svg",
    // title: "Streamer",
    title : "Yayımçılar",
    end: 569,
  },
  {
    id: 3,
    image: "./dice.svg",
    // title: "Games",
    title : "Oyunlar",
    end: 748,
  },
  {
    id: 4,
    image: "./Cup.svg",
    // title: "Tournaments",
    title : "Müsabiqələr",
    end: 327,
  },
];
